spring.application.name=academia-api
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/academia
spring.datasource.username=academia
spring.datasource.password=academia
spring.jpa.hibernate.ddl-auto=update
